type constantType = { [key: string]: string };

export const CONSTANTS: constantType = {
  DUPLICATION: "ALREADY EXISTS",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  USER_NOT_FOUND: "User with this email not found . please sign up",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  SUCCESS: "SUCCESS",
  UNSUCCESS: "UNSUCCESS",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
};
